package exceptions

class SameElementException extends Exception

class UserNotFoundException extends Exception

class UserAlreadyExistsExceptiuon extends Exception

class UserCouldNotBeCreatedException extends Exception